#dataSource.setDriverClassName("com.mysql.jdbc.Driver");
#        dataSource.setUrl("jdbc:mysql://localhost:3306/local_quartz");
#        dataSource.setUsername("root");
#        dataSource.setPassword("root123");


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_quartz
    username: root
    password: root123